"""内置术语起步包：化学/材料方向高频术语（source=seed，用户可改可删）。"""

# (英文, 中文, 领域)
SEED = [
    ("trade-off", "权衡（选择性与渗透率）", "膜科学"),
    ("selectivity", "选择性", "膜科学"),
    ("permeability", "渗透性", "膜科学"),
    ("gas separation", "气体分离", "膜科学"),
    ("mixed-matrix membrane", "混合基质膜", "膜科学"),
    ("polymeric membrane", "聚合物膜", "膜科学"),
    ("free volume", "自由体积", "高分子物理"),
    ("glass transition temperature", "玻璃化转变温度", "高分子物理"),
    ("plasticization", "塑化", "高分子物理"),
    ("molecular sieving", "分子筛分", "分离科学"),
    ("Robeson upper bound", "Robeson 上限", "膜科学"),
    ("cross-linking", "交联", "高分子化学"),
    ("in situ", "原位", "通用"),
    ("metal-organic framework", "金属有机框架", "化学"),
    ("scanning electron microscopy", "扫描电子显微镜", "表征"),
    ("wide-angle X-ray scattering", "广角X射线散射", "表征"),
    ("density functional theory", "密度泛函理论", "计算化学"),
    ("adsorption energy", "吸附能", "计算化学"),
    ("turnover frequency", "转化频率", "催化"),
    ("overpotential", "过电位", "电化学"),
    ("Faradaic efficiency", "法拉第效率", "电化学"),
    ("cyclic voltammetry", "循环伏安法", "电化学"),
    ("rate-determining step", "速率决定步骤", "化学动力学"),
    ("activation energy", "活化能", "化学动力学"),
    ("transition state", "过渡态", "化学"),
    ("coordination environment", "配位环境", "化学"),
    ("control experiment", "对照实验", "通用"),
    ("blank sample", "空白样品", "通用"),
    ("reference sample", "参比样品", "通用"),
    ("reproducibility", "可重复性", "通用"),
    ("limitation", "局限", "通用"),
    ("proof of concept", "概念验证", "通用"),
    ("state-of-the-art", "现有最先进水平", "通用"),
    ("to the best of our knowledge", "据我们所知", "通用"),
]
